GET http://localhost:8080/health
AccessToken:eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiaWF0IjoxNzYyNjA5Mjg4LCJleHAiOjE3NjI2MTEwODgsInR5cGUiOiJhY2Nlc3MiLCJtZW1iZXJJZCI6MSwibWVtYmVyTmFtZSI6Iu2Zjeq4uOuPmSJ9.54tENbIBZDBoBowoNDgd8Jyin65X9oQgO-5ESmYKtiQIJyKPFaomG_YyOcjyaO1P
###
